name: Build Gradle project

on:
  workflow_dispatch:
  pull_request:
  # push:
    branches: [ "main" ]

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
      
    - name: Setup JDK 20 x64
      uses: actions/setup-java@v4
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: gradle
        architecture: x64

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Run build with Gradle Wrapper
      run: |
        cd gradle
        ./gradlew build
    
    - name: Upload Report
      uses: 'actions/upload-artifact@v2'
      with:
        name: report.xml
        # path: ${{ github.workspace }}/build/reports/jacoco/testCoverage/testCoverage.xml
        path: ${{ github.workspace }}/gradle/build/jacoco/test/jacocoTestReport.xml

    - name: Jacoco Report to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.6.1
      with:
        # paths: ${{ github.workspace }}/build/reports/jacoco/testCoverage/testCoverage.xml
        paths: ${{ github.workspace }}/gradle/build/jacoco/test/jacocoTestReport.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 55
        min-coverage-changed-files: 60
        title: '# :lobster: Coverage Report'
        pass-emoji: ':green_circle:'
        fail-emoji: ':red_circle:'
        update-comment: true
        debug-mode: false
    
    - name: Get the Coverage info
      run: |
        echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
        echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"
    
    - name: Fail PR if overall coverage is less than 60%
      if: ${{ steps.jacoco.outputs.coverage-overall < 60.0 }}
      uses: actions/github-script@v6
      with:
        script: |
          core.setFailed('Overall coverage is less than 60%!')